### ISSUE TITLE
วาดตัวละคร

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#1]

**Comment by pairrz** [comment]
![pixil-frame-0 14](https://github.com/minyj
![หันซ้าย](https://github.com/minyjae/project-cpe-g15/assets/139341501/18247074-2301-445f-bf12-c0d6e90dadfd)
ae/project-cpe-g15/assets/139341501/c9
![หลัง](https://github.com/minyjae/project-cpe-g15/assets
![เดินไปข้างหน้า](https://github.com/minyjae/project-cpe-g15/assets/139341501/bd9277f9-674f-46bd-bbc2-023cfaa21d52)
/139341501/ee15263d-e8ff-49f1-b802-a1359e7501e2)
c5990d-4155-4b6f-92f3-22f8fdabe92e)
![เดินขวา](https://github.com/minyjae/project-cpe-g15/assets/139341501/01e0e7bc-2a67-4750-9809-e75b88ec0b61)
