### ISSUE TITLE
ฉากเปิดเกม

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#11]

**Comment by pairrz** [comment]
![Start](https://github.com/minyjae/project-cpe-g15/assets/139341501/3f953600-ce8b-446e-809d-a0c4d3fc8fd1)
![ดีไซน์ที่ยังไม่ได้ตั้งชื่อ](https://github.com/minyjae/project-cpe-g15/assets/139341501/d4be5a8a-5370-42e6-86fc-67c74be61186)
