### ISSUE TITLE
ฉากจบเกม

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#12]

**Comment by pairrz** [comment]
![pixil-frame-0 (14)](https://github.com/minyjae/project-cpe-g15/assets/139341501/3bc2d365-e880-41e2-b803-fb0099b0c396)

**Comment by pairrz** [comment]
![pixil-frame-0 13](https://github.com/minyjae/project-cpe-g15/assets/139341501/ea8a7ae9-2ee8-4c5d-bff6-8b1d3da2e201)
![pixil-frame-0 10](https://github.com/minyjae/project-cpe-g15/assets/139341501/dd106a8a-70e5-48f5-a149-49ce4067dcfd)
