### ISSUE TITLE
โหมดเนื่อเรื่อง

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#14]

**Comment by PKpaopp08** [comment]
[Scratch Project (10).zip](https://github.com/minyjae/project-cpe-g15/files/12565315/Scratch.Project.10.zip)

**Comment by minyjae** [comment]
Adding tree and next stage 
[Scratch Project (10) (5).zip](https://github.com/minyjae/project-cpe-g15/files/12565720/Scratch.Project.10.5.zip)

**Comment by PKpaopp08** [comment]
[PJ Final.zip](https://github.com/minyjae/project-cpe-g15/files/12593252/PJ.Final.zip)
