### ISSUE TITLE
วาดฉาก

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#3]

**Comment by pairrz** [comment]
![pixil-frame-0 (4)](https://github.com/minyjae/project-cpe-g15/assets/139341501/0952e29a-4fc3-451a-8cea-04c7b9ffc216)
![pixil-frame-0 (3)](https://github.com/minyjae/project-cpe-g15/assets/139341501/666d163b-46e2-4040-bf72-dc0c4240cb38)
![pixil-frame-0 (2)](https://github.com/minyjae/project-cpe-g15/assets/139341501/5473e30e-7b73-49f2-b3fe-a6671f559773)
![pixil-frame-0 (1)](https://github.com/minyjae/project-cpe-g15/assets/139341501/6abb283f-5e0f-4879-9156-19e5f2981075)
![pixil-frame-0](https://github.com/minyjae/project-cpe-g15/assets/139341501/3555082a-3ffe-4d04-8790-012b82b94b83)
