### ISSUE TITLE
ตัวละครเดินได้ / โดนรถชนตาย / เก็บไอเทมได้

### ISSUE THREAD

**Issue by PKpaopp08** [minyjae/project-cpe-g15#7]

**Comment by minyjae** [comment]
Test add action script of NPC
[Scratch Project 4 add script.zip](https://github.com/minyjae/project-cpe-g15/files/12512404/Scratch.Project.4.add.script.zip)

**Comment by minyjae** [comment]
Add jump with gliding.
[Scratch Project 5 fix move.zip](https://github.com/minyjae/project-cpe-g15/files/12512415/Scratch.Project.5.fix.move.zip)

**Comment by minyjae** [comment]
Demo 1 for presentation mung 
[mue rai ja sed.zip](https://github.com/minyjae/project-cpe-g15/files/12524998/mue.rai.ja.sed.zip)

**Comment by minyjae** [comment]
Demo final mung
[Demo final mung.zip](https://github.com/minyjae/project-cpe-g15/files/12532529/Demo.final.mung.zip)

**Comment by minyjae** [comment]
Demo final adding sound
[Demo final adding sound.zip](https://github.com/minyjae/project-cpe-g15/files/12532593/Demo.final.adding.sound.zip)
